// Unit 5 单词数据 - 形状与手工 (15词)
var DATA_U5 = [
    { id: 'paper-cut', word: 'paper-cut', cn: '剪纸', linkIcon: '✂️', linkLeft: 'paper<br>cut', linkBridge: '<span class="em">paper</span>(纸)+<span class="hl">cut</span>(切) → 纸切→剪纸', linkDetail: '<b class="em">paper</b>=纸，<b class="hl">cut</b>=切。<br>把纸切成形状→<b>剪纸</b>(paper-cut)<br>中间有连字符！', story: '✂️一张彩纸自己飞起来，一把剪刀开始剪——咔嚓咔嚓！剪出一只小兔子！', sentence: 'I like <b>paper-cut</b>.', spellShow: '<span class="em">paper</span>-<span class="hl">cut</span>', spellTip: '💡 paper(纸)+cut(切)<br>⚠️ 中间有连字符<strong>-</strong>' },
    { id: 'painting', word: 'painting', cn: '绘画；画作', linkIcon: '🎨', linkLeft: 'pain<br>ting', linkBridge: '<span class="em">pain</span>(配)+<span class="hl">ting</span>(听) → 配听→一边看画一边听音乐', linkDetail: '<b class="em">pain</b>(谐音"配")+<b class="hl">ting</b>(谐音"听")<br>→ 画画要搭配音乐来听→<b>绘画</b>(painting)', story: '🎨一支画笔在纸上跳舞，它画什么什么就变活！它画了一朵花，花真的开了！', sentence: 'This is a beautiful <b>painting</b>.', spellShow: '<span class="em">p</span><span class="hl">ai</span><span class="em">n</span><span class="hl">t</span><span class="em">i</span><span class="hl">n</span><span class="em">g</span>', spellTip: '💡 paint+ing<br>⚠️ <span class="hl">ai</span>一起读/eɪ/' },
    { id: 'circle', word: 'circle', cn: '圆形', linkIcon: '⭕', linkLeft: 'cir<br>cle', linkBridge: '<span class="em">cir</span>(瑟)+<span class="hl">cle</span>(扣) → 瑟扣→瑟瑟发抖地把扣子扣成圆形', linkDetail: '<b class="em">cir</b>(谐音"瑟")+<b class="hl">cle</b>(谐音"扣")<br>→ 扣子扣成一个圆→<b>圆形</b>(circle)', story: '⭕你画了一个圆，它滚走了——变成了一个篮球！', sentence: 'Draw a <b>circle</b>.', spellShow: '<span class="em">c</span><span class="hl">ir</span><span class="em">c</span><span class="hl">l</span><span class="em">e</span>', spellTip: '💡 cir(瑟)+cle(扣)<br>⚠️ 开头<strong>cir</strong>不是"cer"' },
    { id: 'triangle', word: 'triangle', cn: '三角形', linkIcon: '🔺', linkLeft: 'tri<br>an<br>gle', linkBridge: '<span class="em">tri</span>(踹)+<span class="hl">an</span>(安)+<span class="em">gle</span>(狗) → 踹安狗→踹安稳的狗，它的头是三角形', linkDetail: '<b class="em">tri</b>（三）+ <b class="hl">angle</b>（角）<br>→ 三个角 → <b>三角形</b>(triangle)', story: '🔺一个三角形跳到你面前，它有三个尖尖的角，每个角都在发光！', sentence: 'The pizza is a <b>triangle</b>.', spellShow: '<span class="em">tri</span><span class="hl">a</span><span class="em">n</span><span class="hl">g</span><span class="em">l</span><span class="hl">e</span>', spellTip: '💡 tri(三)+angle(角)<br>⚠️ 中间是<strong>angle</strong>' },
    { id: 'square', word: 'square', cn: '正方形；正方形的', linkIcon: '🟦', linkLeft: 'squ<br>are', linkBridge: '<span class="em">squ</span>(四块)+<span class="hl">are</span>(是) → 四块是→四块相等的边是正方形', linkDetail: '<b class="em">squ</b>（四块）+ <b class="hl">are</b>（是）<br>→ 四块相等的边→<b>正方形</b>(square)', story: '🟦一块正方形积木落到地上，bounce bounce！它有四条相等的边！', sentence: 'A <b>square</b> has four sides.', spellShow: '<span class="em">s</span><span class="hl">qu</span><span class="em">a</span><span class="hl">r</span><span class="em">e</span>', spellTip: '💡 squ(四块)+are(是)<br>⚠️ <strong>qu</strong>总是一起出现的' },
    { id: 'star', word: 'star', cn: '星星；星形物', linkIcon: '⭐', linkLeft: 's<br>ta<br>r', linkBridge: '<span class="em">s</span>(是)+<span class="hl">ta</span>(他)+<span class="em">r</span>(啊) → 是他啊！天上的星星是他啊！', linkDetail: '<b class="em">s</b>(是)+<b class="hl">ta</b>(他)+<b class="em">r</b>(啊)<br>→ "是他啊！"→抬头看星星→<b>星星</b>(star)', story: '⭐夜晚，一颗星星从天上掉下来，掉到你手里，它还在发光！', sentence: 'I can see a <b>star</b>.', spellShow: '<span class="em">s</span><span class="hl">t</span><span class="em">a</span><span class="hl">r</span>', spellTip: '💡 s(是)+ta(他)+r(啊)<br>⚠️ 只有4个字母' },
    { id: 'rectangle', word: 'rectangle', cn: '矩形；长方形', linkIcon: '▬', linkLeft: 'rec<br>tan<br>gle', linkBridge: '<span class="em">rec</span>(热剋)+<span class="hl">tan</span>(探)+<span class="em">gle</span>(狗) → 热剋探狗→热到被狗追，躲进长方形房间', linkDetail: '<b class="em">rect</b>（直的）+ <b class="hl">angle</b>（角）<br>→ 四个直角的形状→<b>矩形</b>(rectangle)', story: '▬一本长方形书打开了，它的每页都是长方形，越翻越多！', sentence: 'The door is a <b>rectangle</b>.', spellShow: '<span class="em">rec</span><span class="hl">tan</span><span class="em">g</span><span class="hl">l</span><span class="em">e</span>', spellTip: '💡 rect(直的)+angle(角)<br>⚠️ 中间是<strong>tang</strong>' },
    { id: 'clock', word: 'clock', cn: '钟', linkIcon: '🕐', linkLeft: 'cl<br>ock', linkBridge: '<span class="em">cl</span>(可勒)+<span class="hl">ock</span>(奥克) → 可勒奥克→"可勒奥克"像闹钟响', linkDetail: '<b class="em">cl</b>(谐音"可勒")+<b class="hl">ock</b>(谐音"奥克")<br>→ 可勒奥克→闹钟吵醒你！→<b>钟</b>(clock)', story: '🕐一个钟自己敲响了——当！当！当！指针开始跳舞！', sentence: 'The <b>clock</b> shows 3 o\'clock.', spellShow: '<span class="em">c</span><span class="hl">l</span><span class="em">o</span><span class="hl">c</span><span class="em">k</span>', spellTip: '💡 cl(可勒)+ock(奥克)<br>⚠️ 开头<strong>cl</strong>一起读' },
    { id: 'shape', word: 'shape', cn: '形状', linkIcon: '🔷', linkLeft: 'sha<br>pe', linkBridge: '<span class="em">sha</span>(杀)+<span class="hl">pe</span>(破) → 杀破→杀出个形状→形状被打破', linkDetail: '<b class="em">sha</b>(谐音"杀")+<b class="hl">pe</b>(谐音"破")<br>→ 打破→<b>形状</b>(shape)改变了！', story: '🔷一团黏土不断变化形状——圆→方→三角→星！', sentence: 'What <b>shape</b> is it?', spellShow: '<span class="em">sh</span><span class="hl">a</span><span class="em">p</span><span class="hl">e</span>', spellTip: '💡 sha(杀)+pe(破)<br>⚠️ 末尾<strong>e</strong>不发音' },
    { id: 'side', word: 'side', cn: '边', linkIcon: '📐', linkLeft: 'si<br>de', linkBridge: '<span class="em">si</span>(十)+<span class="hl">de</span>(的) → 十的→十个边？太多了！', linkDetail: '<b class="em">si</b>(谐音"十")+<b class="hl">de</b>(的)<br>→ 正方形有四个<b>边</b>(side)，不是十个！', story: '📐一把尺子长出四条腿——每条边都站着一只小蚂蚁！', sentence: 'A triangle has three <b>sides</b>.', spellShow: '<span class="em">s</span><span class="hl">i</span><span class="em">d</span><span class="hl">e</span>', spellTip: '💡 si(十)+de(的)<br>⚠️ 末尾<strong>e</strong>不发音' },
    { id: 'corner', word: 'corner', cn: '角', linkIcon: '🔲', linkLeft: 'cor<br>ner', linkBridge: '<span class="em">cor</span>(靠)+<span class="hl">ner</span>(呢) → 靠呢→靠在角落呢', linkDetail: '<b class="em">cor</b>(谐音"靠")+<b class="hl">ner</b>(谐音"呢")<br>→ 靠在角落呢→<b>角</b>(corner)', story: '🔲一个正方形在房间里找角落——终于找到两面墙的交汇处——这就是角落！', sentence: 'The cat is in the <b>corner</b>.', spellShow: '<span class="em">c</span><span class="hl">or</span><span class="em">n</span><span class="hl">e</span><span class="em">r</span>', spellTip: '💡 cor(靠)+ner(呢)<br>⚠️ <strong>corner</strong>不是corner' },
    { id: 'ask', word: 'ask', cn: '问', linkIcon: '❔', linkLeft: 'as<br>k', linkBridge: '<span class="em">as</span>(啊斯)+<span class="hl">k</span>(可) → 啊斯可→啊斯可汗在问问题', linkDetail: '<b class="em">a</b>(啊)+<b class="hl">s</b>(斯)+<b class="em">k</b>(可)<br>→ 啊斯可→<b>问</b>(ask)问题', story: '❔一只小猫好奇地问"为什么？"——它的嘴边冒出许多问号！', sentence: 'May I <b>ask</b> a question?', spellShow: '<span class="em">a</span><span class="hl">s</span><span class="em">k</span>', spellTip: '💡 a(啊)+s(斯)+k(可)<br>⚠️ 只有3个字母' },
    { id: 'tiger', word: 'tiger', cn: '老虎', linkIcon: '🐯', linkLeft: 'ti<br>ger', linkBridge: '<span class="em">ti</span>(踢)+<span class="hl">ger</span>(哥) → 踢哥→踢老虎哥哥', linkDetail: '<b class="em">ti</b>(谐音"踢")+<b class="hl">ger</b>(谐音"哥")<br>→ 踢老虎哥哥→<b>老虎</b>(tiger)', story: '🐯一只大老虎在丛林里散步，它的条纹在阳光下闪闪发光！嗷！', sentence: 'The <b>tiger</b> is strong.', spellShow: '<span class="em">t</span><span class="hl">i</span><span class="em">g</span><span class="hl">e</span><span class="em">r</span>', spellTip: '💡 ti(踢)+ger(哥)<br>⚠️ <strong>ger</strong>读/gər/不读/dʒər/' },
    { id: 'say', word: 'say', cn: '说', linkIcon: '💬', linkLeft: 'sa<br>y', linkBridge: '<span class="em">sa</span>(撒)+<span class="hl">y</span>(呀) → 撒呀→撒花呀！说得好！', linkDetail: '<b class="em">s</b>(说)+<b class="hl">ay</b>(哎)<br>→ 说哎→<b>说</b>(say)', story: '💬一个嘴巴形状的云朵，每说一句话就下糖果雨！', sentence: 'What did you <b>say</b>?', spellShow: '<span class="em">s</span><span class="hl">a</span><span class="em">y</span>', spellTip: '💡 s(说)+ay(哎)<br>⚠️ <strong>ay</strong>读/eɪ/' },
    { id: 'musical-instrument', word: 'musical instrument', cn: '乐器', linkIcon: '🎵', linkLeft: 'musical<br>instrument', linkBridge: '<span class="em">musical</span>(音乐)+<span class="hl">instrument</span>(工具) → 音乐的工具→乐器', linkDetail: '<b class="em">musical</b>=音乐的 <b class="hl">instrument</b>=工具<br>→ 音乐的工具→<b>乐器</b>(musical instrument)<br>两个词中间有空格！', story: '🎵一把小提琴、一把二胡和一把吉他聚在一起，开始合奏！', sentence: 'The piano is a <b>musical instrument</b>.', spellShow: '<span class="em">musical</span> <span class="hl">instrument</span>', spellTip: '💡 musical(音乐)+instrument(工具)<br>⚠️ instrument有10个字母！in-stru-ment' },
];
if (typeof window !== 'undefined') {
    window.__UNITS = window.__UNITS || {};
    window.__UNITS['u5'] = { name: 'Unit 5', words: DATA_U5 };
}
